### ISSUE TITLE
custom toggle switch and installation error

### ISSUE THREAD

**Issue by flowser** [naifalshaye/toggle-switch#5]
hi? i wish to use this toggle button on a view table whereby, in view table, i have users who can be active or inactive that corresponds to the users table column 'active' having boolean value 1 = active, 0=inactive. my wish is that, in the view table in the index page to be able to activate that user without refreshing the page and also have the switch toggle to have its label as on/Active when switched to be off/Inactive. and also anytime i change the switch it feeds an opposite value to the database. however currently am unable to use your switch as during installation i get 
![image](https://user-images.githubusercontent.com/30996737/45262171-4d126280-b41a-11e8-8bbc-c772b3d3af2a.png)

**Comment by naifalshaye** [comment]
make sure Nova is installed
